### ISSUE TITLE
Request: support for new ui- font families

### ISSUE THREAD

**Issue by lemonmade** [JLHwung/postcss-font-family-system-ui#289]
The CSS Fonts level 4 spec outlines a number of additional ["generic" fonts](https://drafts.csswg.org/css-fonts-4/#ui-serif-def) in the vein of `system-ui`. These include things like `ui-sans-serif`, `ui-monospace`, and a few other, similar keywords.

Should this plugin handle these new families? I would love to be able to use them, but I haven't checked to see what kind of appropriate fallback could even be constructed for these, especially since the support is limited to the next version of Safari right now.

**Comment by JLHwung** [comment]
> Should this plugin handle these new families?

The plugin focuses on `system-ui` polyfills. The other generic font-family types should be supported via different plugins, e.g. (`fangsong` is supported in https://github.com/JLHwung/postcss-font-family-fangsong), though some of new family keywords may not be polyfilled (e.g. explainers for `ui-serif` below)

Per current spec draft

> ui-serif is not expected to map to any font on platforms without an appropriate system font.

It means if user agents do not support `ui-serif`, it should be considered as no-op. Therefore we don't need polyfill `ui-serif` (e.g. as `Times`) for those platforms where a system serif font is not provided, or no such font is _branded_ as a system serif.

> what kind of appropriate fallback could even be constructed for these

Webkit intentionally disallow dot prefixes font-family names ([tweet](https://twitter.com/Litherum/status/1186737454461571072)), that said we can not simply replace `ui-serif` by something like `.AppleSystemUIFontSerif`. If browsers are rolling out platform-specific `ui-serif` equivalents, like `-apple-system` for `system-ui` and `BlinkMacSystemFont` for `ui-serif`, we could polyfill `ui-serif` likewise. Other than that, I don't think we can/should polyfill `ui-serif` and other `ui-*` families.

It is an interesting idea about new plugins. I am gonna close it since it is out of the scope of `system-ui`.
